CREATE TABLE users (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE,
	password VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL);

CREATE TABLE companydetails (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	uid INT(10) NOT NULL,
	category VARCHAR(255) NOT NULL,
	subcategory VARCHAR(255) NOT NULL,
	complainttype VARCHAR(255) UNIQUE,
	state VARCHAR(255) NOT NULL,
	complaint VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    status VARCHAR(255) NOT NULL);


CREATE TABLE admininfo (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
);

CREATE TABLE admininfo (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
);